spring.application.name=shield
spring.threads.virtual.enabled=true
# This tells Spring AI to use Ollama instead of expensive OpenAI
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2